on:
  schedule:
    - cron: "*/5 * * * *"

name: Atualizacao dos dados

jobs:
  atualizacao_dados:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2

      - name: Dependencias do fluxo de trabalho
        run: |
          install.packages(c("GetTDData", "writexl"))
        shell: Rscript {0}

      - name: Generate data
        run: |
          source("R/scrap_ettj.R")
        shell: Rscript {0}

      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "add data"
          git push
